version: 5.1.0
variant: default
logo: /images/avatar.png
head:
    favicon: /images/favicon.jpg
    manifest:
        name:
        short_name:
        start_url:
        theme_color:
        background_color:
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type:
    open_graph:
        title:
        type: blog
        url:
        image:
        site_name:
        author:
        description:
        twitter_card:
        twitter_id:
        twitter_site:
        google_plus:
        fb_admins:
        fb_app_id:
    structured_data:
        title:
        description:
        url:
        author:
        publisher:
        publisher_logo:
        image:
    meta:
        - ''
    rss:
navbar:
    menu:
        é¢è¯•æ”»ç•¥: /interview-strategy.html
        #ç­¾åˆ°é€ä¹¦: /welfare/
        æ¨èè¯¾ç¨‹: /geektime/
        æˆ‘çš„å¼€æº: /opensource/
        å…è´¹ä¹¦ç±: /openbooks/
        #æˆ‘çš„2019: /years/2019.html
        æ—¶é—´è½´: /archives/
# åº•éƒ¨
footer:
    links:
# æ–‡ç« 
article:
    highlight:
        theme: ocean
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/

# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
comment:
    # Name of the comment plugin
    type: gitalk
    owner: hengboy
    repo: learning-tutorials
    client_id: 1560ff459a2b15f5e992
    client_secret: 0289bb92623d9ce2bb25c4ffb454bf8b887fa6a2
    admin: hengboy
sidebar:
    left:
        sticky: false
    right:
        sticky: false
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Widget name
        type: profile
        # Where should the widget be placed, left or right
        position: right
        # Author name to be shown in the profile widget
        author: ç¨‹åºå‘˜ - æ’å®‡å°‘å¹´
        # Title of the author to be shown in the profile widget
        author_title: åˆ†äº«ä¸€äº›é¡¹ç›®å®è·µã€SpringBootã€SpringCloudæ–‡ç« 
        # Author's current location to be shown in the profile widget
        location: å±±ä¸œï¼Œæµå—
        # Path or URL to the avatar to be shown in the profile widget
        avatar:
        # Email address for the Gravatar to be shown in the profile widget
        gravatar:
        # åœ†æ»‘
        avatar_rounded: true
        # Path or URL for the follow button
        follow_link: 'https://gitee.com/hengboy'
    -
        type: links
        position: right
        links:
            ApiBootå®˜ç½‘: https://apiboot.minbox.org
    -
        # çƒ­é—¨æ–‡ç« 
        type: hot_article
        position: right
        # æ ¹æ®æ—¶é—´å€’åºå±•ç¤ºçš„çƒ­é—¨æ–‡ç« æ•°é‡
        show_count: 6
    -
        # å¹¿å‘Š & æ¨å¹¿
        type: advertising
        position: right
        adverts:
            -
                image_url: /images/cover/ApiBootæ¨å¹¿å°é¢.png
                jump_url: /apiboot-all-articles.html
            -
                image_url: /images/æå®¢æ—¶é—´199ç¤¼åŒ….png
                jump_url: http://gk.link/a/10f7u
    -
        # ä¸“é¢˜åˆ—è¡¨
        type: topic
        position: right
        projects:
            -
                title: SpringBoot v1.x åŸºç¡€æ•™ç¨‹
                url: /spring-boot-1-x-articles.html
                image: /images/spring-boot.svg
                desc: å…¨ç½‘å•ç¯‡æ–‡ç« é˜…è¯»é‡è¶…30ä¸‡çš„SpringBootå…è´¹åŸºç¡€æ•™ç¨‹
            -
                title: SpringBoot v2.x åŸºç¡€æ•™ç¨‹
                url: /spring-boot-2-x-articles.html
                image: /images/spring-boot.svg
                desc: æŒç»­åŸºäºSpringBoot v2.3.xç‰ˆæœ¬æ›´æ–°å„ä¸ªç»„ä»¶çš„ä½¿ç”¨ä»¥åŠæºç åˆ†æ
            -
                title: SpringCloud åŸºç¡€æ•™ç¨‹
                url: /spring-cloud-all-articles.html
                image: /images/spring-cloud.svg
                desc: å…¨é¢çš„æ¶µç›–SpringCloudå„ä¸ªç»„ä»¶çš„å…è´¹ä½¿ç”¨åŸºç¡€æ•™ç¨‹
            -
                title: ApiBoot åŸºç¡€æ•™ç¨‹
                url: /apiboot-all-articles.html
                image: /images/api-boot.svg
                desc: æ–°ä¸€ä»£çš„æ¥å£æœåŠ¡è½åœ°è§£å†³æ–¹æ¡ˆï¼ŒåŠ©åŠ›ä½ æˆä¸ºæœåŠ¡æ¶æ„å¸ˆ.
            -
                title: æŠ€æœ¯æ‚è°ˆ
                url: /technical-talk.html
                image: /images/æŠ€æœ¯æ‚è°ˆ.svg
                desc: æ¶µç›–JavaåŸºç¡€ï¼Œæ•°æ®ç»“æ„ä¸ç®—æ³•ï¼ŒLinuxï¼Œä»£ç è§„èŒƒï¼Œæ¶ˆæ¯é˜Ÿåˆ—...
    -
        type: toc
        position: right
        index: true
    -
        type: categories
        position: right
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id:
    bing_webmaster:
        tracking_id:
    busuanzi: false
    cnzz:
        id:
        web_id:
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: UA-127746557-1
    hotjar:
        site_id:
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project:
        security:
    twitter_conversion_tracking:
        pixel_id:
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
search:
    type: baidu
# æ¨èé˜…è¯»
recommended:
        enable: true
        title: ğŸ”¥ ğŸ”¥ ğŸ”¥ ApiBoot ä¸ºç»„ä»¶åŒ–æ„å»ºApiæœåŠ¡è€Œç”Ÿï¼Œæ˜¯æ¥å£æœåŠ¡çš„è½åœ°è§£å†³æ–¹æ¡ˆï¼Œæä¾›äº†ä¸€ç³»åˆ—å¼€ç®±å³ç”¨çš„ç»„ä»¶ã€‚
        url: https://gitee.com/minbox-projects/api-boot